### ISSUE TITLE
Bug Report: Changing users does not update icon or backup names

### ISSUE THREAD

**Issue by impeeza** [BernardoGiordano/Checkpoint#440]
When changing the user inside Checkpoint, the name of new backups and the icon on screen remain as the original user.

1. Open Checkpoint
2. Tap user icon on right lower corner
3. on the Select profile applet, select a different profile
4. The right lower corner icon for user, doesn't change
5. The list of titles does get updated and shows only games with backup, or existing save game data.
6. Try to backup a save data for any game, the proposed name of the backup have the name of the original profile on it

**Expected behavior**
The Right lower icon for user should get updated to the actual user profile.
The name for new backups should get the name of the new profile at end.

**Switch:**
- Entrypoint: Atmosphere 1.25, Hekate 5.6.5
- System version: 13.1.0, EmuNAND
- Checkpoint version: 3.8.0
- SD Card Filesystem: Fat32
- Result code (if available): N/A

I use a application pressing [R] while load to launch Homebrew Loader.

regards from Colombia.

**Comment by GriffinG1** [comment]
Can you confirm that this is graphical only on your side? Just had another user with the issue, and they were still able to properly backup/restore the second user's data despite graphics not updating.

**Comment by ImanolBarba** [comment]
Hi!

As I'm having the same issue, I'm going to verify if, despite the savefiles being made in the other user's name, at least do reflect the other user's progress

**Comment by ImanolBarba** [comment]
After testing, I was able to restore a save from user A to user B's save game and do the opposite as well for a different game, which confirms this is entirely a graphical issue, as the user switching is done correctly.

I would argue in favour of the importance of this issue nonetheless, as an activity as important as savegame backup, which is done for peace of mind, is quickly tarnished by the uncertainty of whether or not you backed up the correct user's :)

**Comment by GriffinG1** [comment]
Just graphical, good to know. Will likely be fixed in the next stable release whenever it is ready.

**Comment by 999px** [comment]
Why was this topic “closed”?
The problem still hasn't been fixed; I just checked in version 3.10.2.
