### ISSUE TITLE
Cannot get title for new Pokemon Quest

### ISSUE THREAD

**Issue by maciak** [BernardoGiordano/Checkpoint#90]
## Issue template

Please fill the fields with all the informations important for the maintainers to get your issue fixed or sorted out.

If you feel it's relevant, please attach screenshots or pictures that could detail the issue more.

* [ ] Issue with Checkpoint for 3DS
* [x] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: hekate_ctcaer_2.0
* System version: 5.0.2
* Checkpoint version: 3.0.1
* Expected behaviour: Pokemon Quest (as a title)
* Encountered behavior: 0x01005D100807A000 (as a title)
* Result code (if available):
* Steps to reproduce:
  * start checkpoint from HBL

**Comment by BernardoGiordano** [comment]
this should be fixed now.

**Comment by maciak** [comment]
it's still not fully fixed. In menu it show properly but it still creates wrong folder on the SD card.

**Comment by BernardoGiordano** [comment]
That's not Checkpoint's fault, but the OS's. It's impossible to write folders to the sd card that contain non-UTF8 characters in their name
